package: sklearn.pipeline
type: Pipeline
steps:
    - - pca
      - package: sklearn.decomposition
        type: PCA
        n_components: 50
    - - svc
      - package: sklearn.svm
        type: SVC
        gamma: 10.0